config/routes.rb
Rails.application.routes.draw do
  root 'site#home'

  get '/about', to: 'site#about', as: :about

  resources :theatres

end

app/models/theatre.rb
class Theatre < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def home
    @theatres = Theatre.all
  end

  def about

  end

end

app/controllers/theatres_controller.rb
class TheatresController < ApplicationController

  def index
    @theatres = Theatre.all
  end

  def show
    @theatre = Theatre.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/theatres_helper.rb
module TheatresHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %><%= link_to 'Theaters', theatres_path %><%= link_to 'About', about_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheatreExpress</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>
<%= yield %>

</body>
</html>

app/views/site/about.html.erb
<h1>About TheatreExpress</h1>
<p>
  This site was the brainchild of Jeremy Weortink, brought to life by Landon West.
  It fills the need to find that special, girly play you've been itching to see and
  don't want to travel to New York to see it.
</p>

app/views/site/home.html.erb
<h1>TheatreExpress</h1>

<div class='search'>
  <form>
    <input type='text' placeholder='search'>
    <input type='submit' value='Search'>
  </form>
</div>

<div class='top_tht'>
  <h2>Top Theaters in SLC</h2>
  <% @theatres.each do |theatre| %>
    <ul>
      <li><%= link_to theatre.name, theatre_path(theatre.id) %></li>
    </ul>
  <% end %>
</div>

app/views/theatres/index.html.erb
<h1>Theaters</h1>

<% @theatres.each do |theatre| %>
  <ul>
    <li><%= link_to theatre.name, theatre_path(theatre.id) %></li>
  </ul>
<% end %>

app/views/theatres/show.html.erb
<h1><%= @theatre.name %></h1>

<ul>
  <li><%= @theatre.website %></li>
  <li><%= @theatre.address %></li>
  <li><%= @theatre.phone %></li>
  <li><%= @theatre.description %></li>
</ul>

<div>
  <h2>Current Plays</h2>
  
</div>

<%= link_to "Back to Theaters", theatres_path %>